class Move:
    def __init__(self,index,name,type,category,power,accuracy):
        self.name = name
        self.type = type
        self.category = category
        self.power = power
        self.accuracy = accuracy
        self.x = 11
        self.y = 7 + index * 8

def get_move(move_id):
    for move_data in all_moves:
        if move_data["id"] == move_id:
            return Move(move_data["id"], move_data["name"], move_data["type"], move_data["category"], move_data["power"], move_data["accuracy"])
    return None

all_moves = [
    {"id": 1, "name": "Absorb", "type": "Grass", "category": "Special", "power": 20, "accuracy": 100, "pp": 25},
    {"id": 2, "name": "Acid", "type": "Poison", "category": "Special", "power": 40, "accuracy": 100, "pp": 30},
    {"id": 3, "name": "Acid Armor", "type": "Poison", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    {"id": 4, "name": "Agility", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    {"id": 5, "name": "Amnesia", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    {"id": 6, "name": "Aurora Beam", "type": "Ice", "category": "Special", "power": 65, "accuracy": 100, "pp": 20},
    {"id": 7, "name": "Barrage", "type": "Normal", "category": "Physical", "power": 15, "accuracy": 85, "pp": 20},
    {"id": 8, "name": "Barrier", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    {"id": 9, "name": "Bind", "type": "Normal", "category": "Physical", "power": 15, "accuracy": 85, "pp": 20},
    {"id": 10, "name": "Bite", "type": "Dark", "category": "Physical", "power": 60, "accuracy": 100, "pp": 25},
    {"id": 11, "name": "Blizzard", "type": "Ice", "category": "Special", "power": 110, "accuracy": 70, "pp": 5},
    {"id": 12, "name": "Body Slam", "type": "Normal", "category": "Physical", "power": 85, "accuracy": 100, "pp": 15},
    # {"id": 13, "name": "Bone Club", "type": "Ground", "category": "Physical", "power": 65, "accuracy": 85, "pp": 20},
    # {"id": 14, "name": "Bonemerang", "type": "Ground", "category": "Physical", "power": 50, "accuracy": 90, "pp": 10},
    # {"id": 15, "name": "Bubble", "type": "Water", "category": "Special", "power": 40, "accuracy": 100, "pp": 30},
    # {"id": 16, "name": "Bubble Beam", "type": "Water", "category": "Special", "power": 65, "accuracy": 100, "pp": 20},
    # {"id": 17, "name": "Clamp", "type": "Water", "category": "Physical", "power": 35, "accuracy": 85, "pp": 10},
    # {"id": 18, "name": "Comet Punch", "type": "Normal", "category": "Physical", "power": 18, "accuracy": 85, "pp": 15},
    # {"id": 19, "name": "Confuse Ray", "type": "Ghost", "category": "Status", "power": None, "accuracy": 100, "pp": 10},
    # {"id": 20, "name": "Confusion", "type": "Psychic", "category": "Special", "power": 50, "accuracy": 100, "pp": 25},
    # {"id": 21, "name": "Constrict", "type": "Normal", "category": "Physical", "power": 10, "accuracy": 100, "pp": 35},
    # {"id": 22, "name": "Conversion", "type": "Normal", "category": "Special", "power": None, "accuracy": None, "pp": 35},
    # {"id": 23, "name": "Counter", "type": "Fighting", "category": "Physical", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 24, "name": "Crabhammer", "type": "Water", "category": "Physical", "power": 100, "accuracy": 90, "pp": 10},
    # {"id": 25, "name": "Cut", "type": "Normal", "category": "Physical", "power": 50, "accuracy": 95, "pp": 30},
    # {"id": 26, "name": "Defense Curl", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 40},
    # {"id": 27, "name": "Dig", "type": "Ground", "category": "Physical", "power": 80, "accuracy": 100, "pp": 10},
    # {"id": 28, "name": "Disable", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 29, "name": "Dizzy Punch", "type": "Normal", "category": "Physical", "power": 70, "accuracy": 100, "pp": 10},
    # {"id": 30, "name": "Double Kick", "type": "Fighting", "category": "Physical", "power": 30, "accuracy": 100, "pp": 30},
    # {"id": 31, "name": "Double Slap", "type": "Normal", "category": "Physical", "power": 15, "accuracy": 85, "pp": 10},
    # {"id": 32, "name": "Double Team", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 15},
    # {"id": 33, "name": "Double-Edge", "type": "Normal", "category": "Physical", "power": 120, "accuracy": 100, "pp": 15},
    # {"id": 34, "name": "Dragon Rage", "type": "Dragon", "category": "Special", "power": None, "accuracy": 100, "pp": 10},
    # {"id": 35, "name": "Dream Eater", "type": "Psychic", "category": "Special", "power": 100, "accuracy": 100, "pp": 15},
    # {"id": 36, "name": "Drill Peck", "type": "Flying", "category": "Physical", "power": 80, "accuracy": 100, "pp": 20},
    # {"id": 37, "name": "Earthquake", "type": "Ground", "category": "Physical", "power": 100, "accuracy": 100, "pp": 10},
    # {"id": 38, "name": "Egg Bomb", "type": "Normal", "category": "Physical", "power": 100, "accuracy": 75, "pp": 10},
    # {"id": 39, "name": "Ember", "type": "Fire", "category": "Special", "power": 40, "accuracy": 100, "pp": 25},
    # {"id": 40, "name": "Explosion", "type": "Normal", "category": "Physical", "power": 250, "accuracy": 100, "pp": 5},
    # {"id": 41, "name": "Fire Blast", "type": "Fire", "category": "Special", "power": 110, "accuracy": 85, "pp": 5},
    # {"id": 42, "name": "Fire Punch", "type": "Fire", "category": "Physical", "power": 75, "accuracy": 100, "pp": 15},
    # {"id": 43, "name": "Fire Spin", "type": "Fire", "category": "Special", "power": 35, "accuracy": 85, "pp": 15},
    # {"id": 44, "name": "Fissure", "type": "Ground", "category": "Physical", "power": None, "accuracy": 30, "pp": 5},
    # {"id": 45, "name": "Flamethrower", "type": "Fire", "category": "Special", "power": 90, "accuracy": 100, "pp": 15},
    # {"id": 46, "name": "Flash", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 47, "name": "Fly", "type": "Flying", "category": "Physical", "power": 90, "accuracy": 95, "pp": 15},
    # {"id": 48, "name": "Focus Energy", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 49, "name": "Fury Attack", "type": "Normal", "category": "Physical", "power": 15, "accuracy": 85, "pp": 20},
    # {"id": 50, "name": "Fury Cutter", "type": "Bug", "category": "Physical", "power": 40, "accuracy": 95, "pp": 20},
    # {"id": 51, "name": "Fury Swipes", "type": "Normal", "category": "Physical", "power": 18, "accuracy": 80, "pp": 15},
    # {"id": 52, "name": "Glare", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 30},
    # {"id": 53, "name": "Growl", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 40},
    # {"id": 54, "name": "Growth", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 40},
    # {"id": 55, "name": "Guillotine", "type": "Normal", "category": "Physical", "power": None, "accuracy": 30, "pp": 5},
    # {"id": 56, "name": "Gust", "type": "Flying", "category": "Special", "power": 40, "accuracy": 100, "pp": 35},
    # {"id": 57, "name": "Harden", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 58, "name": "Haze", "type": "Ice", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 59, "name": "Headbutt", "type": "Normal", "category": "Physical", "power": 70, "accuracy": 100, "pp": 15},
    # {"id": 60, "name": "High Jump Kick", "type": "Fighting", "category": "Physical", "power": 130, "accuracy": 90, "pp": 10},
    # {"id": 61, "name": "Horn Attack", "type": "Normal", "category": "Physical", "power": 65, "accuracy": 100, "pp": 25},
    # {"id": 62, "name": "Horn Drill", "type": "Normal", "category": "Physical", "power": None, "accuracy": 30, "pp": 5},
    # {"id": 63, "name": "Hydro Pump", "type": "Water", "category": "Special", "power": 110, "accuracy": 80, "pp": 5},
    # {"id": 64, "name": "Hyper Beam", "type": "Normal", "category": "Special", "power": 150, "accuracy": 90, "pp": 5},
    # {"id": 65, "name": "Hyper Fang", "type": "Normal", "category": "Physical", "power": 80, "accuracy": 90, "pp": 15},
    # {"id": 66, "name": "Hypnosis", "type": "Psychic", "category": "Status", "power": None, "accuracy": 60, "pp": 20},
    # {"id": 67, "name": "Ice Beam", "type": "Ice", "category": "Special", "power": 90, "accuracy": 100, "pp": 10},
    # {"id": 68, "name": "Ice Punch", "type": "Ice", "category": "Physical", "power": 75, "accuracy": 100, "pp": 15},
    # {"id": 69, "name": "Ice Shard", "type": "Ice", "category": "Physical", "power": 40, "accuracy": 100, "pp": 30},
    # {"id": 70, "name": "Icy Wind", "type": "Ice", "category": "Special", "power": 55, "accuracy": 95, "pp": 15},
    # {"id": 71, "name": "Karate Chop", "type": "Fighting", "category": "Physical", "power": 50, "accuracy": 100, "pp": 25},
    # {"id": 72, "name": "Kinesis", "type": "Psychic", "category": "Status", "power": None, "accuracy": 80, "pp": 15},
    # {"id": 73, "name": "Leech Life", "type": "Bug", "category": "Physical", "power": 80, "accuracy": 100, "pp": 10},
    # {"id": 74, "name": "Leech Seed", "type": "Grass", "category": "Status", "power": None, "accuracy": 90, "pp": 10},
    # {"id": 75, "name": "Leer", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 30},
    # {"id": 76, "name": "Lick", "type": "Ghost", "category": "Physical", "power": 30, "accuracy": 100, "pp": 30},
    # {"id": 77, "name": "Light Screen", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 78, "name": "Lovely Kiss", "type": "Normal", "category": "Status", "power": None, "accuracy": 75, "pp": 10},
    # {"id": 79, "name": "Low Kick", "type": "Fighting", "category": "Physical", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 80, "name": "Meditate", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 40},
    # {"id": 81, "name": "Mega Drain", "type": "Grass", "category": "Special", "power": 40, "accuracy": 100, "pp": 15},
    # {"id": 82, "name": "Mega Kick", "type": "Normal", "category": "Physical", "power": 120, "accuracy": 75, "pp": 5},
    # {"id": 83, "name": "Mega Punch", "type": "Normal", "category": "Physical", "power": 80, "accuracy": 85, "pp": 20},
    # {"id": 84, "name": "Metronome", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 85, "name": "Mimic", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 86, "name": "Minimize", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 87, "name": "Mirror Move", "type": "Flying", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 88, "name": "Mist", "type": "Ice", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 89, "name": "Night Shade", "type": "Ghost", "category": "Special", "power": None, "accuracy": 100, "pp": 15},
    # {"id": 90, "name": "Pay Day", "type": "Normal", "category": "Physical", "power": 40, "accuracy": 100, "pp": 20},
    # {"id": 91, "name": "Peck", "type": "Flying", "category": "Physical", "power": 35, "accuracy": 100, "pp": 35},
    # {"id": 92, "name": "Petal Dance", "type": "Grass", "category": "Special", "power": 120, "accuracy": 100, "pp": 10},
    # {"id": 93, "name": "Pin Missile", "type": "Bug", "category": "Physical", "power": 25, "accuracy": 95, "pp": 20},
    # {"id": 94, "name": "Poison Gas", "type": "Poison", "category": "Status", "power": None, "accuracy": 90, "pp": 40},
    # {"id": 95, "name": "Poison Powder", "type": "Poison", "category": "Status", "power": None, "accuracy": 75, "pp": 35},
    # {"id": 96, "name": "Poison Sting", "type": "Poison", "category": "Physical", "power": 15, "accuracy": 100, "pp": 35},
    # {"id": 97, "name": "Pound", "type": "Normal", "category": "Physical", "power": 40, "accuracy": 100, "pp": 35},
    # {"id": 98, "name": "Powder Snow", "type": "Ice", "category": "Special", "power": 40, "accuracy": 100, "pp": 25},
    # {"id": 99, "name": "Powder", "type": "Bug", "category": "Status", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 100, "name": "Psybeam", "type": "Psychic", "category": "Special", "power": 65, "accuracy": 100, "pp": 20},
    # {"id": 101, "name": "Psychic", "type": "Psychic", "category": "Special", "power": 90, "accuracy": 100, "pp": 10},
    # {"id": 102, "name": "Psywave", "type": "Psychic", "category": "Special", "power": None, "accuracy": 80, "pp": 15},
    # {"id": 103, "name": "Quick Attack", "type": "Normal", "category": "Physical", "power": 40, "accuracy": 100, "pp": 30},
    # {"id": 104, "name": "Rage", "type": "Normal", "category": "Physical", "power": 20, "accuracy": 100, "pp": 20},
    # {"id": 105, "name": "Rain Dance", "type": "Water", "category": "Status", "power": None, "accuracy": None, "pp": 5},
    # {"id": 106, "name": "Razor Leaf", "type": "Grass", "category": "Physical", "power": 55, "accuracy": 95, "pp": 25},
    # {"id": 107, "name": "Razor Wind", "type": "Normal", "category": "Special", "power": 80, "accuracy": 75, "pp": 10},
    # {"id": 108, "name": "Recover", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 109, "name": "Reflect", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 110, "name": "Rest", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 111, "name": "Roar", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 112, "name": "Rock Slide", "type": "Rock", "category": "Physical", "power": 75, "accuracy": 90, "pp": 10},
    # {"id": 113, "name": "Rock Throw", "type": "Rock", "category": "Physical", "power": 50, "accuracy": 90, "pp": 15},
    # {"id": 114, "name": "Rolling Kick", "type": "Fighting", "category": "Physical", "power": 60, "accuracy": 85, "pp": 15},
    # {"id": 115, "name": "Rollout", "type": "Rock", "category": "Physical", "power": 30, "accuracy": 90, "pp": 20},
    # {"id": 116, "name": "Roost", "type": "Flying", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 117, "name": "Sand Attack", "type": "Ground", "category": "Status", "power": None, "accuracy": 100, "pp": 15},
    # {"id": 118, "name": "Sand Tomb", "type": "Ground", "category": "Physical", "power": 35, "accuracy": 85, "pp": 15},
    # {"id": 119, "name": "Scratch", "type": "Normal", "category": "Physical", "power": 40, "accuracy": 100, "pp": 35},
    # {"id": 120, "name": "Screech", "type": "Normal", "category": "Status", "power": None, "accuracy": 85, "pp": 40},
    # {"id": 121, "name": "Seismic Toss", "type": "Fighting", "category": "Physical", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 122, "name": "Self-Destruct", "type": "Normal", "category": "Physical", "power": 200, "accuracy": 100, "pp": 5},
    # {"id": 123, "name": "Sharpen", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 124, "name": "Sing", "type": "Normal", "category": "Status", "power": None, "accuracy": 55, "pp": 15},
    # {"id": 125, "name": "Skull Bash", "type": "Normal", "category": "Physical", "power": 130, "accuracy": 100, "pp": 10},
    # {"id": 126, "name": "Sky Attack", "type": "Flying", "category": "Physical", "power": 140, "accuracy": 90, "pp": 5},
    # {"id": 127, "name": "Sky Uppercut", "type": "Fighting", "category": "Physical", "power": 85, "accuracy": 90, "pp": 15},
    # {"id": 128, "name": "Slam", "type": "Normal", "category": "Physical", "power": 80, "accuracy": 75, "pp": 20},
    # {"id": 129, "name": "Slash", "type": "Normal", "category": "Physical", "power": 70, "accuracy": 100, "pp": 20},
    # {"id": 130, "name": "Sleep Powder", "type": "Grass", "category": "Status", "power": None, "accuracy": 75, "pp": 15},
    # {"id": 131, "name": "Sludge", "type": "Poison", "category": "Special", "power": 65, "accuracy": 100, "pp": 20},
    # {"id": 132, "name": "Smog", "type": "Poison", "category": "Special", "power": 30, "accuracy": 70, "pp": 20},
    # {"id": 133, "name": "Smokescreen", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 20},
    # {"id": 134, "name": "Soft-Boiled", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 135, "name": "Solar Beam", "type": "Grass", "category": "Special", "power": 120, "accuracy": 100, "pp": 10},
    # {"id": 136, "name": "Sonic Boom", "type": "Normal", "category": "Special", "power": None, "accuracy": 90, "pp": 20},
    # {"id": 137, "name": "Spike Cannon", "type": "Normal", "category": "Physical", "power": 20, "accuracy": 100, "pp": 15},
    # {"id": 138, "name": "Splash", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 40},
    # {"id": 139, "name": "Spore", "type": "Grass", "category": "Status", "power": None, "accuracy": 100, "pp": 15},
    # {"id": 140, "name": "Steel Wing", "type": "Steel", "category": "Physical", "power": 70, "accuracy": 90, "pp": 25},
    # {"id": 141, "name": "Stomp", "type": "Normal", "category": "Physical", "power": 65, "accuracy": 100, "pp": 20},
    # {"id": 142, "name": "Strength", "type": "Normal", "category": "Physical", "power": 80, "accuracy": 100, "pp": 15},
    # {"id": 143, "name": "String Shot", "type": "Bug", "category": "Status", "power": None, "accuracy": 95, "pp": 40},
    # {"id": 144, "name": "Struggle", "type": "Normal", "category": "Physical", "power": 50, "accuracy": None, "pp": None},
    # {"id": 145, "name": "Stun Spore", "type": "Poison", "category": "Status", "power": None, "accuracy": 75, "pp": 30},
    # {"id": 146, "name": "Submission", "type": "Fighting", "category": "Physical", "power": 80, "accuracy": 80, "pp": 20},
    # {"id": 147, "name": "Substitute", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 148, "name": "Super Fang", "type": "Normal", "category": "Physical", "power": None, "accuracy": 90, "pp": 10},
    # {"id": 149, "name": "Superpower", "type": "Fighting", "category": "Physical", "power": 120, "accuracy": 100, "pp": 5},
    # {"id": 150, "name": "Supersonic", "type": "Normal", "category": "Status", "power": None, "accuracy": 55, "pp": 20},
    # {"id": 151, "name": "Surf", "type": "Water", "category": "Special", "power": 90, "accuracy": 100, "pp": 15},
    # {"id": 152, "name": "Swift", "type": "Normal", "category": "Special", "power": 60, "accuracy": None, "pp": 20},
    # {"id": 153, "name": "Swords Dance", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 154, "name": "Synthesis", "type": "Grass", "category": "Status", "power": None, "accuracy": None, "pp": 5},
    # {"id": 155, "name": "Tackle", "type": "Normal", "category": "Physical", "power": 40, "accuracy": 100, "pp": 35},
    # {"id": 156, "name": "Tail Whip", "type": "Normal", "category": "Status", "power": None, "accuracy": 100, "pp": 30},
    # {"id": 157, "name": "Take Down", "type": "Normal", "category": "Physical", "power": 90, "accuracy": 85, "pp": 20},
    # {"id": 158, "name": "Teleport", "type": "Psychic", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 159, "name": "Thrash", "type": "Normal", "category": "Physical", "power": 120, "accuracy": 100, "pp": 10},
    # {"id": 160, "name": "Thunder", "type": "Electric", "category": "Special", "power": 110, "accuracy": 70, "pp": 10},
    # {"id": 161, "name": "Thunder Fang", "type": "Electric", "category": "Physical", "power": 65, "accuracy": 95, "pp": 15},
    # {"id": 162, "name": "Thunder Punch", "type": "Electric", "category": "Physical", "power": 75, "accuracy": 100, "pp": 15},
    # {"id": 163, "name": "Thunder Shock", "type": "Electric", "category": "Special", "power": 40, "accuracy": 100, "pp": 30},
    # {"id": 164, "name": "Thunder Wave", "type": "Electric", "category": "Status", "power": None, "accuracy": 90, "pp": 20},
    # {"id": 165, "name": "Thunderbolt", "type": "Electric", "category": "Special", "power": 90, "accuracy": 100, "pp": 15},
    # {"id": 166, "name": "Tri Attack", "type": "Normal", "category": "Special", "power": 80, "accuracy": 100, "pp": 10},
    # {"id": 167, "name": "Twineedle", "type": "Bug", "category": "Physical", "power": 25, "accuracy": 100, "pp": 20},
    # {"id": 168, "name": "Twister", "type": "Dragon", "category": "Special", "power": 40, "accuracy": 100, "pp": 20},
    # {"id": 169, "name": "U-turn", "type": "Bug", "category": "Physical", "power": 70, "accuracy": 100, "pp": 20},
    # {"id": 170, "name": "Vice Grip", "type": "Normal", "category": "Physical", "power": 55, "accuracy": 100, "pp": 30},
    # {"id": 171, "name": "Vine Whip", "type": "Grass", "category": "Physical", "power": 45, "accuracy": 100, "pp": 25},
    # {"id": 172, "name": "Vital Throw", "type": "Fighting", "category": "Physical", "power": 70, "accuracy": None, "pp": 10},
    # {"id": 173, "name": "Volt Tackle", "type": "Electric", "category": "Physical", "power": 120, "accuracy": 100, "pp": 15},
    # {"id": 174, "name": "Wing Attack", "type": "Flying", "category": "Physical", "power": 60, "accuracy": 100, "pp": 35},
    # {"id": 175, "name": "Withdraw", "type": "Water", "category": "Status", "power": None, "accuracy": None, "pp": 40},
    # {"id": 176, "name": "Wrap", "type": "Normal", "category": "Physical", "power": 15, "accuracy": 90, "pp": 20},
    # {"id": 177, "name": "X Accuracy", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 178, "name": "X Attack", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 179, "name": "X Defense", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 180, "name": "X Sp. Atk", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 20},
    # {"id": 181, "name": "X Sp. Def", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 30},
    # {"id": 182, "name": "Yawn", "type": "Normal", "category": "Status", "power": None, "accuracy": None, "pp": 10},
    # {"id": 183, "name": "Zap Cannon", "type": "Electric", "category": "Special", "power": 120, "accuracy": 50, "pp": 5},
    # {"id": 184, "name": "Zen Headbutt", "type": "Psychic", "category": "Physical", "power": 80, "accuracy": 90, "pp": 15}
]
